### ISSUE TITLE
Failed to send OTP

### ISSUE THREAD

**Issue by Abhis2004** [saran-surya/email_auth#41] opened 2021-09-28 10:00 UTC
FIRST TRY ERROR
I/flutter ( 3861): email-auth >> Remote server is not available -- using test server --
I/flutter ( 3861): email-auth >> ❗ Warning this is not reliable on production
I/flutter ( 3861): email-auth >> The remote server configurations are valid
I/flutter ( 3861): --- Package Error ---
I/flutter ( 3861): Unable to access server. 😑

SECOND TRY ERROR
I/flutter ( 3861): email-auth >> The remote server configurations are valid
I/flutter ( 3861): email-auth >> Failed to send OTP ❌
I/flutter ( 3861): email-auth >> Message from server :: null

*Sorry for bothering you again and again*

**Comment by saran-surya** [comment] 2021-09-28 15:56
Hi Yes, the test server is down for maintenance. And the remote server URL might be the issue, because if it would have reached the server. There will surely be a error message. Kindly send your server url. And please do maintain the discussion in the same issue.

Thanks

**Comment by Abhis2004** [comment] 2021-09-28 16:10
https://carvaan.herokuapp.com

**Comment by Abhis2004** [comment] 2021-09-28 16:12
I left the server key as it is what was given when I imported the repo

**Comment by saran-surya** [comment] 2021-09-28 16:24
> I left the server key as it is what was given when I imported the repo

Now that is the issue, The server key is needed. Kindly add the server key from your config.env file from the production server in your local machine.

**Comment by Abhis2004** [comment] 2021-09-28 16:44
mailID = my mail id
password = my password
mailPort = port
SERVER_API_KEY = api key

# ------ Flutter guidelines ------
                    
# In your Flutter project create a auth.config.dart file in the root of the lib folder,
                    
# copy the following line into the file, and pass it to the email_auth package.    
                    
# var remoteServerConfiguration = {"server" : "server url", "serverKey" : "HERE WAS A KEY WHEN I IMPORTED THE PROJECT AND I USED THIS KEY IN MY FLUTTER PROJECT
"};

**Comment by saran-surya** [comment] 2021-09-28 16:58
> mailID = my mail id password = my password mailPort = port SERVER_API_KEY = api key
> 
> # ------ Flutter guidelines ------
> # In your Flutter project create a auth.config.dart file in the root of the lib folder,
> # copy the following line into the file, and pass it to the email_auth package.
> # var remoteServerConfiguration = {"server" : "server url", "serverKey" : "HERE WAS A KEY WHEN I IMPORTED THE PROJECT AND I USED THIS KEY IN MY FLUTTER PROJECT
> "};

I still don't get it, how is the api key with spaces added in, please read the steps in the GitHub page, I still have a feeling that you are not following all the instructions. Kindly check them once

**Comment by Abhis2004** [comment] 2021-09-28 17:03
![Uploading Screenshot (34).png…]()

**Comment by Abhis2004** [comment] 2021-09-28 17:04
![Screenshot (34)](https://user-images.githubusercontent.com/73050271/135132863-bae7a697-9ffc-4be6-b389-50ed33fcdd89.png)

**Comment by Abhis2004** [comment] 2021-09-28 17:05
this file is in my production server

**Comment by saran-surya** [comment] 2021-09-28 17:06
> this file is in my production server

No this will not work, you should generate them using the command

```npx email-auth-node --generate```

That's what I suggested you to read the complete steps. Please look into them

**Comment by Abhis2004** [comment] 2021-09-28 17:07
I have generated thats how i made the account and gotserver api key

**Comment by saran-surya** [comment] 2021-09-28 17:07
> I have generated thats how i made the account and gotserver api key

Then please use the server api key in your flutter app also, it will not work withou the server api key

**Comment by Abhis2004** [comment] 2021-09-28 17:08
var remoteServerConfiguration = {"server" : "https://carvaan.herokuapp.com",
    "serverKey" : "UDujOQ",
  };

this is what i have written in my flutter project
please tell me where i have to pass server api key

**Comment by saran-surya** [comment] 2021-09-28 17:11
> var remoteServerConfiguration = {"server" : "https://carvaan.herokuapp.com", "serverKey" : "UDujOQ", };
> 
> this is what i have written in my flutter project please tell me where i have to pass server api key

This is fine, still confused regarding the failure, because i see many are using production servers now, and they are all fine.

Did you add the buildbacks in heroku ?

**Comment by Abhis2004** [comment] 2021-09-28 17:11
yes 
i can send ss if you want

**Comment by saran-surya** [comment] 2021-09-28 17:12
> yes i can send ss if you want

Yes please,  and if possible attach the logs from heroku also.

**Comment by Abhis2004** [comment] 2021-09-28 17:12
![Screenshot (35)](https://user-images.githubusercontent.com/73050271/135134013-282e16a0-7976-475d-85ec-c921c9ede0af.png)

**Comment by Abhis2004** [comment] 2021-09-28 17:13
wherwe i can find heroku logs

**Comment by saran-surya** [comment] 2021-09-28 17:15
> where i can find heroku logs

Not required, I want you to do the following.

Open the project in vs code. Press ctrl and click on the EmailAuth class and reach out to the package file. Kindly let me know once you are able to see the code of the package in your editor

**Comment by Abhis2004** [comment] 2021-09-28 17:17
yes i can see

**Comment by Abhis2004** [comment] 2021-09-28 17:18
please help me out from this situation my users are uninstalling my app

**Comment by saran-surya** [comment] 2021-09-28 17:19
> yes i can see

I want you to go to line number 62 and change the following.

![Screenshot_20210928-224636_Chrome](https://user-images.githubusercontent.com/59312489/135134743-0591efca-07ff-4618-8f64-e593870c41a6.jpg)

Instead of _data["error"] replace it with _data, save it and run the application. And paste in the logs of it

**Comment by Abhis2004** [comment] 2021-09-28 17:20
![Screenshot (36)](https://user-images.githubusercontent.com/73050271/135135114-ca7d400a-5a4c-4b07-bfaa-1623fed571b2.png)

**Comment by Abhis2004** [comment] 2021-09-28 17:21
what i have to change here

**Comment by saran-surya** [comment] 2021-09-28 17:21
> what i have to change here

In line number 62.

 Instead of _data["error"] replace it with _data, save it and run the application. And paste in the logs of it

**Comment by Abhis2004** [comment] 2021-09-28 17:24
i changed _data["error"] with _data but still I'm getting this error

I/flutter ( 6468): email-auth >> The remote server configurations are valid
I/flutter ( 6468): email-auth >> Failed to send OTP ❌
I/flutter ( 6468): email-auth >> Message from server :: null

**Comment by saran-surya** [comment] 2021-09-28 17:27
Un comment line number 52 and save it and rebuild the application. Not restart, rebuild.

**Comment by Abhis2004** [comment] 2021-09-28 17:29
it's rebuilding btw thanks for helping me you are grate person and above that you are a grate developer

**Comment by Abhis2004** [comment] 2021-09-28 17:30
I/flutter ( 6810): email-auth >> The remote server configurations are valid
I/flutter ( 6810): {status: 404, mail: araj86907@gmail.com, success: false, message: Unable to send mail}
I/flutter ( 6810): email-auth >> Failed to send OTP ❌
I/flutter ( 6810): email-auth >> Message from server :: {status: 404, mail: araj86907@gmail.com, success: false, message: Unable to send mail}

**Comment by saran-surya** [comment] 2021-09-28 17:32
> I/flutter ( 6810): email-auth >> The remote server configurations are valid I/flutter ( 6810): {status: 404, mail: [araj86907@gmail.com](mailto:araj86907@gmail.com), success: false, message: Unable to send mail} I/flutter ( 6810): email-auth >> Failed to send OTP ❌ I/flutter ( 6810): email-auth >> Message from server :: {status: 404, mail: [araj86907@gmail.com](mailto:araj86907@gmail.com), success: false, message: Unable to send mail}

Hey have you enabled the allow less secure apps for the account ?

**Comment by Abhis2004** [comment] 2021-09-28 17:33
![Screenshot (37)](https://user-images.githubusercontent.com/73050271/135136945-91163d9c-d7eb-458b-841d-25c178d7829f.png)

**Comment by saran-surya** [comment] 2021-09-28 17:36
So things are fine from the flutter part, your server is now the issue, we need to check them. Kindly install heroku CLI and put in the logs here. If you have issues kindly visit the heroku docs for the CLI installation

**Comment by Abhis2004** [comment] 2021-09-28 17:49
![Screenshot (38)](https://user-images.githubusercontent.com/73050271/135139283-eac4b2f2-b44e-4fe9-a05a-9b3e00fd2120.png)

**Comment by Abhis2004** [comment] 2021-09-28 17:49
hey I'm logged in what I have to do next

**Comment by saran-surya** [comment] 2021-09-28 17:51
> hey I'm logged in what I have to do next

```heroku logs --tail```

**Comment by Abhis2004** [comment] 2021-09-28 17:52
![Screenshot (39)](https://user-images.githubusercontent.com/73050271/135139707-546cc4ce-d59a-4c8d-b841-8097fe2b683d.png)

**Comment by Abhis2004** [comment] 2021-09-28 17:56
what next

**Comment by saran-surya** [comment] 2021-09-28 17:58
> what next



> what next

https://github.com/saran-surya/email_auth/issues/41#issuecomment-929489019

**Comment by Abhis2004** [comment] 2021-09-28 18:00
I didn't understand

**Comment by Abhis2004** [comment] 2021-09-28 18:00
I ran the command you asked

**Comment by saran-surya** [comment] 2021-09-28 18:01
> I ran the command you asked

Paste in the logs here please

**Comment by Abhis2004** [comment] 2021-09-28 18:03
I never worked with heroku before can you tell me what I have to do to get the logs

**Comment by saran-surya** [comment] 2021-09-28 18:04
> I never worked with heroku before can you tell me what I have to do to get the logs

Run the command ```heroku logs --tail```

**Comment by Abhis2004** [comment] 2021-09-28 18:05
C:\Users\araj8>heroku logs --tail
 »   Warning: heroku update available from 7.53.0 to 7.59.0.
 »   Error: Missing required flag:
 »     -a, --app APP  app to run command against
 »   See more help with --help

**Comment by Abhis2004** [comment] 2021-09-28 18:07
C:\Users\araj8>heroku logs --app=carvaan --tail
 »   Warning: heroku update available from 7.53.0 to 7.59.0.
2021-09-28T09:52:26.008740+00:00 app[web.1]: Server error cannot send mail : section 1
2021-09-28T09:52:26.008741+00:00 app[web.1]:
2021-09-28T09:52:44.116638+00:00 app[web.1]: -------- Server Key Verification ---------
2021-09-28T09:52:44.116792+00:00 app[web.1]: true
2021-09-28T09:52:44.116836+00:00 app[web.1]: ------------------------------------------
2021-09-28T09:52:44.119986+00:00 heroku[router]: at=info method=GET path="/test/dart" host=carvaan.herokuapp.com request_id=c43b5234-baba-445a-903c-e1c52928b1b1 fwd="103.209.71.209" dyno=web.1 connect=0ms service=5ms status=200 bytes=817 protocol=https
2021-09-28T09:52:44.837574+00:00 app[web.1]: (535, b'5.7.8 Username and Password not accepted. Learn more at\n5.7.8  https://support.google.com/mail/?p=BadCredentials 18sm5085994qtz.49 - gsmtp')
2021-09-28T09:52:44.837583+00:00 app[web.1]: Server error cannot send mail : section 1
2021-09-28T09:52:44.837583+00:00 app[web.1]:
2021-09-28T09:52:44.839117+00:00 heroku[router]: at=info method=GET path="/dart/auth/araj86907@gmail.com?CompanyName=carvaan&key=UDujOQ&otpLength=5" host=carvaan.herokuapp.com request_id=fa794c02-cac5-4520-8ff7-0e47ff382527 fwd="103.209.71.209" dyno=web.1 connect=0ms service=723ms status=200 bytes=887 protocol=https
2021-09-28T09:55:24.887350+00:00 heroku[router]: at=info method=GET path="/test/dart" host=carvaan.herokuapp.com request_id=fd5fe2f6-93d1-45a5-9d37-bc8eefc7fbf7 fwd="103.209.71.209" dyno=web.1 connect=0ms service=1ms status=200 bytes=817 protocol=https
2021-09-28T09:56:11.769311+00:00 app[web.1]: -------- Server Key Verification ---------
2021-09-28T09:56:11.769415+00:00 app[web.1]: true
2021-09-28T09:56:11.769438+00:00 app[web.1]: ------------------------------------------
2021-09-28T09:56:11.775428+00:00 heroku[router]: at=info method=GET path="/test/dart" host=carvaan.herokuapp.com request_id=fae092d4-383a-48eb-93ed-2c0eaae98253 fwd="103.209.71.209" dyno=web.1 connect=0ms service=1ms status=200 bytes=817 protocol=https
2021-09-28T09:56:12.486592+00:00 app[web.1]: (535, b'5.7.8 Username and Password not accepted. Learn more at\n5.7.8  https://support.google.com/mail/?p=BadCredentials x3sm14219593qkl.107 - gsmtp')
2021-09-28T09:56:12.486603+00:00 app[web.1]: Server error cannot send mail : section 1
2021-09-28T09:56:12.486604+00:00 app[web.1]:
2021-09-28T09:56:12.487836+00:00 heroku[router]: at=info method=GET path="/dart/auth/araj86907@gmail.com?CompanyName=carvaan&key=UDujOQ&otpLength=5" host=carvaan.herokuapp.com request_id=e3115d16-34c0-4c11-81f4-94fed90f490c fwd="103.209.71.209" dyno=web.1 connect=0ms service=719ms status=200 bytes=887 protocol=https
2021-09-28T09:57:19.251795+00:00 app[web.1]: -------- Server Key Verification ---------
2021-09-28T09:57:19.251954+00:00 app[web.1]: true
2021-09-28T09:57:19.251987+00:00 app[web.1]: ------------------------------------------
2021-09-28T09:57:19.257190+00:00 heroku[router]: at=info method=GET path="/test/dart" host=carvaan.herokuapp.com request_id=b2f17001-84ca-477a-a072-6d8ed3600e65 fwd="103.209.71.209" dyno=web.1 connect=0ms service=4ms status=200 bytes=817 protocol=https
2021-09-28T09:57:19.996625+00:00 app[web.1]: (535, b'5.7.8 Username and Password not accepted. Learn more at\n5.7.8  https://support.google.com/mail/?p=BadCredentials h66sm14549101qkc.5 - gsmtp')
2021-09-28T09:57:19.996648+00:00 app[web.1]: Server error cannot send mail : section 1
2021-09-28T09:57:19.996649+00:00 app[web.1]:
2021-09-28T09:57:19.997529+00:00 heroku[router]: at=info method=GET path="/dart/auth/araj86907@gmail.com?CompanyName=carvaan&key=UDujOQ&otpLength=5" host=carvaan.herokuapp.com request_id=0c862ee1-f3fb-4b0e-9add-0f84759227ea fwd="103.209.71.209" dyno=web.1 connect=0ms service=747ms status=200 bytes=887 protocol=https
2021-09-28T09:58:35.541472+00:00 app[web.1]: -------- Server Key Verification ---------
2021-09-28T09:58:35.541569+00:00 app[web.1]: true
2021-09-28T09:58:35.541590+00:00 app[web.1]: ------------------------------------------
2021-09-28T09:58:35.545761+00:00 heroku[router]: at=info method=GET path="/test/dart" host=carvaan.herokuapp.com request_id=db0e58fc-0bec-46a0-ba6a-e1385736e028 fwd="103.209.71.209" dyno=web.1 connect=0ms service=1ms status=200 bytes=817 protocol=https
2021-09-28T09:58:36.239476+00:00 app[web.1]: (535, b'5.7.8 Username and Password not accepted. Learn more at\n5.7.8  https://support.google.com/mail/?p=BadCredentials n20sm14648368qkk.135 - gsmtp')
2021-09-28T09:58:36.239484+00:00 app[web.1]: Server error cannot send mail : section 1
2021-09-28T09:58:36.239484+00:00 app[web.1]:
2021-09-28T09:58:36.240347+00:00 heroku[router]: at=info method=GET path="/dart/auth/araj86907@gmail.com?CompanyName=carvaan&key=UDujOQ&otpLength=5" host=carvaan.herokuapp.com request_id=6f892481-b3f1-4e56-b2f1-771ebb32b5c3 fwd="103.209.71.209" dyno=web.1 connect=0ms service=699ms status=200 bytes=887 protocol=https
2021-09-28T10:30:52.191949+00:00 heroku[web.1]: Idling
2021-09-28T10:30:52.194467+00:00 heroku[web.1]: State changed from up to down
2021-09-28T10:30:54.055019+00:00 heroku[web.1]: Stopping all processes with SIGTERM
2021-09-28T10:30:54.240450+00:00 heroku[web.1]: Process exited with status 143
2021-09-28T16:10:27.820255+00:00 heroku[web.1]: Unidling
2021-09-28T16:10:27.832375+00:00 heroku[web.1]: State changed from down to starting
2021-09-28T16:10:33.111008+00:00 heroku[web.1]: Starting process with command `npm start`
2021-09-28T16:10:34.123258+00:00 app[web.1]:
2021-09-28T16:10:34.123271+00:00 app[web.1]: > email-auth-node@0.0.1 start /app
2021-09-28T16:10:34.123272+00:00 app[web.1]: > node server/index.js
2021-09-28T16:10:34.123272+00:00 app[web.1]:
2021-09-28T16:10:34.239063+00:00 app[web.1]: server started
2021-09-28T16:10:34.239200+00:00 app[web.1]: port 35151
2021-09-28T16:10:34.741524+00:00 heroku[web.1]: State changed from starting to up
2021-09-28T16:10:35.885230+00:00 heroku[router]: at=info method=GET path="/" host=carvaan.herokuapp.com request_id=288ec333-4b51-42e1-9d35-ce920c2aa672 fwd="103.38.130.150" dyno=web.1 connect=0ms service=7ms status=304 bytes=739 protocol=https
2021-09-28T16:10:36.246442+00:00 heroku[router]: at=info method=GET path="/favicon.ico" host=carvaan.herokuapp.com request_id=fa628967-9f8d-4f7b-b491-770806045d63 fwd="103.38.130.150" dyno=web.1 connect=0ms service=3ms status=404 bytes=667 protocol=https
2021-09-28T16:23:32.167310+00:00 heroku[router]: at=info method=GET path="/" host=carvaan.herokuapp.com request_id=0a593fef-05f0-498e-97ab-e7acd799fdeb fwd="157.49.154.49" dyno=web.1 connect=0ms service=2ms status=200 bytes=818 protocol=https
2021-09-28T16:23:32.515924+00:00 heroku[router]: at=info method=GET path="/favicon.ico" host=carvaan.herokuapp.com request_id=077e1c04-7651-4499-ad26-82cfb0b6a7ef fwd="157.49.154.49" dyno=web.1 connect=0ms service=1ms status=404 bytes=667 protocol=https
2021-09-28T16:40:05.200630+00:00 heroku[router]: at=info method=GET path="/test/dart" host=carvaan.herokuapp.com request_id=bfbbecd9-1bd2-4caa-8acb-ffd0f67a2b52 fwd="103.38.130.150" dyno=web.1 connect=0ms service=2ms status=200 bytes=817 protocol=https
2021-09-28T16:40:17.597580+00:00 heroku[router]: at=info method=GET path="/test/dart" host=carvaan.herokuapp.com request_id=179b8e22-392c-4688-81ab-c22ed9aad956 fwd="103.38.130.150" dyno=web.1 connect=0ms service=1ms status=200 bytes=817 protocol=https
2021-09-28T16:40:17.659313+00:00 app[web.1]: -------- Server Key Verification ---------
2021-09-28T16:40:17.660049+00:00 app[web.1]: true
2021-09-28T16:40:17.660089+00:00 app[web.1]: ------------------------------------------
2021-09-28T16:40:18.495263+00:00 heroku[router]: at=info method=GET path="/dart/auth/araj86907@gmail.com?CompanyName=carvaan&key=UDujOQ&otpLength=5" host=carvaan.herokuapp.com request_id=dcbc8fcd-31df-49a9-8966-f5c115b9fa5b fwd="103.38.130.150" dyno=web.1 connect=0ms service=839ms status=200 bytes=887 protocol=https
2021-09-28T16:40:18.495372+00:00 app[web.1]: (535, b'5.7.8 Username and Password not accepted. Learn more at\n5.7.8  https://support.google.com/mail/?p=BadCredentials r13sm15833700qkk.73 - gsmtp')
2021-09-28T16:40:18.495381+00:00 app[web.1]: Server error cannot send mail : section 1
2021-09-28T16:40:18.495382+00:00 app[web.1]:
2021-09-28T17:13:55.176862+00:00 heroku[router]: at=info method=HEAD path="/" host=carvaan.herokuapp.com request_id=3d55190c-a555-4705-a379-5eb38133688d fwd="217.182.175.162" dyno=web.1 connect=0ms service=2ms status=200 bytes=789 protocol=https
2021-09-28T17:23:03.082641+00:00 heroku[router]: at=info method=GET path="/test/dart" host=carvaan.herokuapp.com request_id=eafe25af-97b2-4c0d-bdcd-ea3df1dace0e fwd="103.38.130.150" dyno=web.1 connect=0ms service=1ms status=200 bytes=817 protocol=https
2021-09-28T17:23:52.760673+00:00 app[web.1]: -------- Server Key Verification ---------
2021-09-28T17:23:52.760810+00:00 app[web.1]: true
2021-09-28T17:23:52.760833+00:00 app[web.1]: ------------------------------------------
2021-09-28T17:23:52.836377+00:00 heroku[router]: at=info method=GET path="/test/dart" host=carvaan.herokuapp.com request_id=df925d70-7d4c-4443-8f9f-06c9c70f63d2 fwd="103.38.130.150" dyno=web.1 connect=0ms service=1ms status=200 bytes=817 protocol=https
2021-09-28T17:23:53.513986+00:00 heroku[router]: at=info method=GET path="/dart/auth/araj86907@gmail.com?CompanyName=carvaan&key=UDujOQ&otpLength=5" host=carvaan.herokuapp.com request_id=fcb3e0bc-10e3-4017-9f50-6156dd2b28aa fwd="103.38.130.150" dyno=web.1 connect=0ms service=756ms status=200 bytes=887 protocol=https
2021-09-28T17:23:53.514782+00:00 app[web.1]: (535, b'5.7.8 Username and Password not accepted. Learn more at\n5.7.8  https://support.google.com/mail/?p=BadCredentials m68sm15508936qkb.105 - gsmtp')
2021-09-28T17:23:53.514788+00:00 app[web.1]: Server error cannot send mail : section 1
2021-09-28T17:23:53.514789+00:00 app[web.1]:
2021-09-28T17:23:55.050174+00:00 heroku[router]: at=info method=GET path="/test/dart" host=carvaan.herokuapp.com request_id=82533e4b-0076-4996-932b-2245d0fb48ca fwd="103.38.130.150" dyno=web.1 connect=0ms service=2ms status=200 bytes=817 protocol=https
2021-09-28T17:23:55.141993+00:00 app[web.1]: -------- Server Key Verification ---------
2021-09-28T17:23:55.142099+00:00 app[web.1]: true
2021-09-28T17:23:55.142125+00:00 app[web.1]: ------------------------------------------
2021-09-28T17:23:55.813133+00:00 app[web.1]: (535, b'5.7.8 Username and Password not accepted. Learn more at\n5.7.8  https://support.google.com/mail/?p=BadCredentials d24sm15046293qka.7 - gsmtp')
2021-09-28T17:23:55.813141+00:00 app[web.1]: Server error cannot send mail : section 1
2021-09-28T17:23:55.813142+00:00 app[web.1]:
2021-09-28T17:23:55.817948+00:00 heroku[router]: at=info method=GET path="/dart/auth/araj86907@gmail.com?CompanyName=carvaan&key=UDujOQ&otpLength=5" host=carvaan.herokuapp.com request_id=3af484e5-9670-4f6e-bedd-7b827b9d2286 fwd="103.38.130.150" dyno=web.1 connect=0ms service=673ms status=200 bytes=887 protocol=https
2021-09-28T17:30:05.173197+00:00 heroku[router]: at=info method=GET path="/test/dart" host=carvaan.herokuapp.com request_id=aa6d8ae5-b94a-49c1-9b7c-147a0c92285a fwd="103.38.130.150" dyno=web.1 connect=3ms service=1ms status=200 bytes=817 protocol=https
2021-09-28T17:30:12.976197+00:00 app[web.1]: -------- Server Key Verification ---------
2021-09-28T17:30:12.976331+00:00 app[web.1]: true
2021-09-28T17:30:12.976356+00:00 app[web.1]: ------------------------------------------
2021-09-28T17:30:13.021896+00:00 heroku[router]: at=info method=GET path="/test/dart" host=carvaan.herokuapp.com request_id=606df934-5817-4e26-bcf3-16511aceb577 fwd="103.38.130.150" dyno=web.1 connect=0ms service=2ms status=200 bytes=817 protocol=https
2021-09-28T17:30:13.733368+00:00 app[web.1]: (535, b'5.7.8 Username and Password not accepted. Learn more at\n5.7.8  https://support.google.com/mail/?p=BadCredentials r6sm6318352qtp.34 - gsmtp')
2021-09-28T17:30:13.733375+00:00 app[web.1]: Server error cannot send mail : section 1
2021-09-28T17:30:13.733375+00:00 app[web.1]:
2021-09-28T17:30:13.734439+00:00 heroku[router]: at=info method=GET path="/dart/auth/araj86907@gmail.com?CompanyName=carvaan&key=UDujOQ&otpLength=5" host=carvaan.herokuapp.com request_id=a9ee604e-2667-4ce0-b69b-9000185a0a88 fwd="103.38.130.150" dyno=web.1 connect=0ms service=759ms status=200 bytes=887 protocol=https
2021-09-28T17:36:31.270236+00:00 heroku[router]: at=info method=GET path="/" host=carvaan.herokuapp.com request_id=03baa30b-32af-44f2-9126-565dafffcc41 fwd="157.49.161.219" dyno=web.1 connect=0ms service=1ms status=200 bytes=818 protocol=https
2021-09-28T17:36:31.820400+00:00 heroku[router]: at=info method=GET path="/favicon.ico" host=carvaan.herokuapp.com request_id=3ae1796d-d00f-453a-94f5-bd113f08e3e0 fwd="157.49.161.219" dyno=web.1 connect=0ms service=2ms status=404 bytes=667 protocol=https
2021-09-28T17:36:48.560180+00:00 heroku[router]: at=info method=GET path="/" host=carvaan.herokuapp.com request_id=b0c22099-00b3-46af-877c-609169ad5a29 fwd="157.49.161.219" dyno=web.1 connect=0ms service=1ms status=200 bytes=818 protocol=https
2021-09-28T17:39:57.860407+00:00 heroku[router]: at=info method=GET path="/saransurya199@gmail.com?key=UDujOQ&companyName=sample" host=carvaan.herokuapp.com request_id=6851f20d-035f-4e30-9d89-99d99992763c fwd="157.49.161.219" dyno=web.1 connect=0ms service=1ms status=404 bytes=679 protocol=https
2021-09-28T17:40:33.221571+00:00 app[web.1]: -------- Server Key Verification ---------
2021-09-28T17:40:33.221688+00:00 app[web.1]: true
2021-09-28T17:40:33.221709+00:00 app[web.1]: ------------------------------------------
2021-09-28T17:40:33.984945+00:00 app[web.1]: (535, b'5.7.8 Username and Password not accepted. Learn more at\n5.7.8  https://support.google.com/mail/?p=BadCredentials c6sm5076437qtc.77 - gsmtp')
2021-09-28T17:40:33.984955+00:00 app[web.1]: Server error cannot send mail : section 1
2021-09-28T17:40:33.984956+00:00 app[web.1]:
2021-09-28T17:40:33.987615+00:00 heroku[router]: at=info method=GET path="/dart/auth/saransurya199@gmail.com?key=UDujOQ&companyName=sample" host=carvaan.herokuapp.com request_id=05e4ba29-0645-49d6-b8b3-7cfb247cfc58 fwd="157.49.161.219" dyno=web.1 connect=0ms service=765ms status=200 bytes=891 protocol=https

**Comment by Abhis2004** [comment] 2021-09-28 18:08
here is the log

**Comment by saran-surya** [comment] 2021-09-28 18:09
> here is the log

It's the issue from your side, the credentials you gave in are wrong the log says it all, kindly have a look at the credentials. Did you change the port number in any case ?

**Comment by Abhis2004** [comment] 2021-09-28 18:09
no

**Comment by saran-surya** [comment] 2021-09-28 18:10
> no

Your credentials are wrong

-09-28T17:40:33.984945+00:00 app[web.1]: (535, b'5.7.8 Username and Password not accepted.

Kindly read the logs.

**Comment by Abhis2004** [comment] 2021-09-28 18:11
what should I do now

**Comment by saran-surya** [comment] 2021-09-28 18:12
> what should I do now

Check your gmail accounts user name and password

**Comment by Abhis2004** [comment] 2021-09-28 18:13
I changed my gamil account password this evening is that causing problem?

**Comment by Abhis2004** [comment] 2021-09-28 18:15
> > what should I do now
> 
> Check your gmail account's user name and password

my account's user name and password is correct

**Comment by saran-surya** [comment] 2021-09-28 18:17
> I changed my gamil account password this evening is that causing problem?

Maybe, I think the issue is clearly from your side, check them. And also revert back the changes made to the source code. The repo and the server is fine. Kindly check your credentials and try again. I am closing this issue as it is getting out of scope. Kindly comment back of there is issue with the package.

Thanks. Happy coding

**Closed by saran-surya** 2021-09-28 18:17 UTC
Labels: question
