### ISSUE TITLE
User not receiving otp

### ISSUE THREAD

**Issue by Abhis2004** [saran-surya/email_auth#25] opened 2021-09-03 05:15 UTC
I can send otp successfully but the user not receiving the otp mail.

**Comment by saran-surya** [comment] 2021-09-03 06:38
Kindly attach the screenshots of the debug console and the session Name, Are you using a custom server ? or the test server.

**Comment by kentmartin12** [comment] 2021-09-03 09:39
Hi, I have this issue too, where the OTP is successfully sent, but I didn't receive the OTP in mail. And I use my custom server, but it seems the package said that I didn't have it. Here are the screenshots on my debug console, thank you very much!
![Screenshot 2021-09-03 163659](https://user-images.githubusercontent.com/53167038/131984687-a00c727a-0703-457d-9fa1-a6f348545700.png)

**Comment by saran-surya** [comment] 2021-09-03 16:54
Hi,
So the issue is that you have to pass the relative path to the server,
lindly remove the last forward slash, and the remote server is set to go.

**Comment by saran-surya** [comment] 2021-09-03 17:05
Hi @Abhis2004 , So is your issue resolved ?

**Comment by Abhis2004** [comment] 2021-09-03 17:07
Yes sir my issue solved. Thanks!

**Comment by saran-surya** [comment] 2021-09-03 17:11
Thanks, closing this issue.

**Closed by saran-surya** 2021-09-03 17:11 UTC
Labels: question
